# Generated by Django 4.0.4 on 2022-05-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_alter_comentario_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
