# Generated by Django 4.0.4 on 2022-05-11 03:53

from django.db import migrations, models
import neoexit_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('neoexit_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', neoexit_auth.models.NeoexitUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
